### ISSUE TITLE
ClassCastException in InsertStatement

### ISSUE THREAD

**Issue by hassomehide** [nortal/petit#9]
The runtime type of "key" is BigDecimal, which causes a ClassCastException in InsertStatement.java:129:

    javax.persistence.PersistenceException: InsertStatement.exec: unable to write bean primary key
     at com.nortal.petit.orm.statement.InsertStatement.exec(InsertStatement.java:133) ~[petit-orm-1.0.3-SNAPSHOT.jar:?]
    ...
    Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@1610713
     at com.nortal.petit.beanmapper.ReflectionProperty.write(ReflectionProperty.java:41) ~[petit-beanmapper-1.0.3-SNAPSHOT.jar:?]
     at com.nortal.petit.orm.statement.InsertStatement.exec(InsertStatement.java:129) ~[petit-orm-1.0.3-SNAPSHOT.jar:?]

**Comment by AlrikP** [comment]
Problem is that Oracle JDBC Driver JDBC 3.0 support has its quirks.
For example in PostgreSQL the following statement initialization "con.prepareStatement(getSql(), Statement.RETURN_GENERATED_KEYS);" allows querying generated keys from PreparedStatement getGeneratedKeys() method. In Oracle this returns ROWID's.
In order to get generated keys you must tell Oracle which column contains generated keys:
con.prepareStatement(getSql(), new String[] { idColumn });

**Comment by AlrikP** [comment]
Fixed in version 1.0.4
